# Generated by Django 5.2.17 on 2026-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='category',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='title',
            new_name='school_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
