# Generated by Django 5.2.17 on 2026-09-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_education_starred_by_alter_experience_starred_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'permissions': [('can_add_education', 'Can add an education card'), ('can_delete_education', 'Can delete an education card'), ('can_change_education', 'Can change information on an education card')]},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'permissions': [('can_add_experience', 'Can add an experience card'), ('can_delete_experience', 'Can delete an experience card'), ('can_change_experience', 'Can change information on an experience card')]},
        ),
    ]
